### ISSUE TITLE
Errors in the notebook 14b-errormaps-demo

### ISSUE THREAD

**Issue by ctroupin** [gher-uliege/Diva-Workshops#17]
The [CI](https://github.com/gher-uliege/Diva-Workshops/actions/runs/4083682523/jobs/7039495943) reported an error in notebook `14b-errormaps-demo` so I tried to run it and got some issues:

1. In cell [15] (as per GitHub):
```julia
ploterr(aerrora)
title("Error using errormap version $method");
```
gives an error
```julia
PyError ($(Expr(:escape, :(ccall(#= /home/ctroupin/.julia/packages/PyCall/ygXW2/src/pyfncall.jl:43 =# @pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, pyargsptr, kw))))) <class 'ValueError'>
ValueError('too many values to unpack (expected 2)')
```
2. In cell [16]:
```julia
aerror,method = DIVAnd_errormap(mask,(pm,pn),(xi,yi),(obslon,obslat),obsval.-mean(obsval),len,epsilon2,
    s;
    method = :precise,
    Bscale = false)
ploterr(aerror)
title("Error using automatic version $method");
```
gives the same error. In fact when I try to access the variable `aerror` I get this:
```julia
julia> aerror
'Y': ASCII/Unicode U+0059 (category Lu: Letter, uppercase)
```

## Solutions

I could make it work with those changes below though I'm not sure why it failed?

1. Add an index `[1]` to the array: 
```julia
ploterr(aerrora[1])
title("Error using errormap version $method");
```
2. Replace `:precise` by `"precise"` in the function call:
```julia
aerror,method = DIVAnd_errormap(mask,(pm,pn),(xi,yi),(obslon,obslat),obsval.-mean(obsval),len,epsilon2,
    s;
    method = "precise",
    Bscale = false)
```

**Comment by jmbeckers** [comment]
Normally is already corrected in my branch

**Comment by ctroupin** [comment]
OK thanks! I was surprised by the badge
[![Build Status](https://github.com/gher-uliege/Diva-Workshops/workflows/CI/badge.svg)](https://github.com/gher-uliege/Diva-Workshops/actions)
but it will turn green again soon ;)
